// kz_vue/src/components/AddDeveloperForm.vue
<template>
    <form @submit.prevent="handleSubmit">
        <label>Name:  </label>
        <input type="text" required v-model="name">
        <label>Address:</label>
        <textarea required v-model="address"></textarea>
        <button>Add Developer</button>
    </form>
</template>

<script>

export default {
    inject:['storeDevelopers'],
    name: 'AddDeveloperForm',
    data(){
        return {
            name:'',
            address:''
        }
    },
    methods:{
        handleSubmit(){
            let developer = {
                name:this.name,address:this.address
            }
            this.storeDevelopers.methods.addDeveloper(developer);
            this.name = '';
            this.address = '';
        }
    }
}
</script>

// kz_react/src/components/AddDeveloperForm.js
import { useState,useContext} from "react";
import {DeveloperContext} from '../context/DevelopersContext';


function AddDeveloperForm() {
    const [name,setName] = useState('');
    const [address,setAddress] = useState('');

    const {addDeveloper} = useContext(DeveloperContext);
    
    const handleSubmit = (e) => {
        let developer = {
            name,address
        }
        addDeveloper(developer);
        e.preventDefault();
    }

    return (
        <>
            <form onSubmit={handleSubmit}>
                <label>Name:  </label>
                <input type="text" required value={name} onChange={ (e) => { setName(e.target.value)} } />
                <label>Address:</label>
                <textarea required value={address} onChange={ (e) => { setAddress(e.target.value)} } ></textarea>
                <button>Add Developer</button>
            </form>
        </>
    );
}

export default AddDeveloperForm;
