// kz_react/src/components/Developer.js
import {useState} from 'react';
import {useContext} from 'react';
import {DeveloperContext} from '../context/DevelopersContext';

function Developer(props) {
    const [showAddress,setShowAddress] = useState(false);

    const {deleteDeveloper} = useContext(DeveloperContext);

    return (
        <div className="developer">
            <div className="actions">
                <h3 onClick={()=>setShowAddress(!showAddress)}>{props.developer.name}</h3>
                <div className="icons">
                    <span className="material-icons" onClick={()=>{deleteDeveloper(props.developer)}}>delete</span>
                </div>
            </div>
            {showAddress ? <div className="details"> <p>{props.developer.address}</p> </div>:''}
        </div>
    );
}

export default Developer;

// kz_vue/src/components/Developer.vue
<template>
  <div class="developer">
    <div class="actions">
      <h3 @click="showAddress = !showAddress">{{ developer.name }}</h3>
      <div class="icons">
        <span class="material-icons" @click="handleDelete">delete</span>
      </div>
    </div>
    <div v-if="showAddress" class="details">
      <p>{{ developer.address }}</p>
    </div>
  </div>
</template>

<script>


export default {
    inject:['storeDevelopers'],
    data(){
      return {
        showAddress:false
      }
    },
    methods:{
      handleDelete(){
        this.storeDevelopers.methods.deleteDeveloper(this.developer.id);
      }
    },
    name: 'Developer',
    props:['developer']
}
</script>
