// kz_react/src/components/SingleDeveloper.js
import "./SingleDeveloper.css";
import {useState} from 'react';

function SingleDeveloper(props) {
    const [showAddress, setShowAddress] = useState(false);
    
    return (
        <div className="developer">
            <div className="actions">
                <h3 onClick={()=>setShowAddress(!showAddress)}>{props.developer.name}</h3>
                <div className="icons">
                    <span className="material-icons">delete</span>
                </div>
            </div>
            {showAddress ? <div className="details"> <p>{props.developer.address}</p> </div>:''}
        </div>
    );
}

export default SingleDeveloper;

// kz_vue/src/components/SingleDeveloper.vue
<template>
  <div class="developer">
    <div class="actions">
      <h3 @click="showAddress = !showAddress">{{ developer.name }}</h3>
      <div class="icons">
        <span class="material-icons">delete</span>
      </div>
    </div>
    <div v-if="showAddress" class="details">
      <p>{{ developer.address }}</p>
    </div>
  </div>
</template>

<script>
export default {
    props: ["developer"],
    data() {
        return {
            showAddress: false
        };
    },
}
</script>

<style src="./SingleDeveloper.css">
</style>
